print("hello world")
print("jack")
print("jack sparrow")
print("hi,i am fasih.")
print ("25")
print (2*3)
print ("2+5+9")
print ("hello,","I ","am","fasih.")
print ("fasih","is","20","years","old.")
print (5, "+",4 "=", 5+4)
